### ISSUE TITLE
10.7 + 10.8 Support

### ISSUE THREAD

**Issue by henrytill** [copumpkin/nixpkgs#26]
Results of `nm -gjp /usr/lib/system/libsystem_*.dylib` on 10.7.5:

https://gist.github.com/henrytill/db4b99d022feca446296

**Updated**: for your convenience, here they are again in a single file, just like the 10.8.5 symbols:
https://gist.github.com/henrytill/73fac6143a4003baec4e

**Comment by jwiegley** [comment]
The same for 10.8.5:

https://gist.github.com/db3603813d3d8f1d571e

**Comment by copumpkin** [comment]
Pure-darwin now has a deployment target of 10.7. I don't know if it actually works on 10.7. Can someone somehow compile a list of what we're giving up by preserving compatibility back then? I know that prior to 10.7, there was no proper thread-local storage, so I wouldn't want to go back that far. I think that's the main thing that we give up on the "linker" level. It would be really nice if someone could grep a bunch of the official Apple headers for availability macros that don't exist on 10.7, to make a more informed decisions on what we're giving up.

**Comment by shlevy** [comment]
FWIW, I'm in favor of "don't fix it till it's broke" approach. If there are no known issues with supporting `10.7`, great! If we find an issue due to that, OK let's bump to 10.8 then.
