### ISSUE TITLE
Figure out what to do about iconv wrt GHC

### ISSUE THREAD

**Issue by joelteon** [copumpkin/nixpkgs#37]
GHC's DLL loader uses `dlopen(libiconv.dylib)` without an absolute path. This fails in the sandbox since `/usr/lib/libiconv.dylib` is off-limits. There are a few solutions:

1. Add libiconv's lib directory to `DYLD{_FALLBACK}_LIBRARY_PATH` in `$ghc/nix-support/setup-hook`. This works, but obviously causes libiconv to be in scope at runtime for any package that indirectly depends on GHC, which may not be desirable.
2. `wrapProgram $prog --prefix DYLD_LIBRARY_PATH "${libiconv}/lib"` for any executable that uses the GHC API. This includes doctest, haddock, ghci, and so on. This is also not nice, but at least better than option 1 because it doesn't contaminate the whole package ecosystem. However, it requires more work.
3. Make GHC dlopen an absolute path. This is the ideal solution, but I have no idea how to actually do it, and #ghc doesn't seem to either. Still investigating.

**Comment by shlevy** [comment]
3, 3, a million times 3. Let me know if I can help dig in.

**Comment by joelteon** [comment]
Turns out this was embarrassingly trivial!

In the ghc-7.4.2 binary, this needed to be added to `preConfigure`:

``` nix
stdenv.lib.optionalString stdenv.isDarwin ''
  find . -name base.buildinfo \
    -exec sed -i "s@extra-lib-dirs: @extra-lib-dirs: ${libiconv}/lib@" {} \;
''
```

while in ghc-7.8.4's source build, this had to be added to `buildMK`:

``` nix
stdenv.lib.optionalString stdenv.isDarwin ''
  libraries/base_CONFIGURE_OPTS += --configure-option=--with-iconv-includes="${libiconv}/include"
  libraries/base_CONFIGURE_OPTS += --configure-option=--with-iconv-libraries="${libiconv}/lib"
''
```

This is because GHC's DLL loader makes three tries to load DLLs:

1. Search `extra-lib-dirs` for the file in question
2. Search the compiler's builtin files, i.e. `clang --print-file-name foo.dylib`
3. Just dlopen the name of the library, assuming that the OS's dynamic loader can find it

Though GHC could build correctly since libiconv was a buildInput, it wasn't added to base's extra-lib-dirs.

These solutions have the benefit of fixing both the dlopen problem and the linker not being able to find libraries.
