### ISSUE TITLE
Building ruby libraries fails in sandbox

### ISSUE THREAD

**Issue by joelteon** [copumpkin/nixpkgs#38]
`gem install` prints out something like this:

```
ERROR:  Could not find a valid gem '/nix/store/19x1yx4rlggj7ghgdyhqnr6536pjyz61-mini_portile-0.6.1.gem' (>= 0) in any repository
```

even if given `--local --ignore-dependencies`

**Comment by copumpkin** [comment]
Can you give more context on how to reproduce this? If you install ruby, everything's fine, but then using it breaks?

**Comment by copumpkin** [comment]
Ping @joelteon

**Comment by joelteon** [comment]
Try to build `terminal-notifier` for example in the sandbox.

**Comment by copumpkin** [comment]
Can you test that this is okay in pure-darwin head and close it if it is?

**Comment by joelteon** [comment]
We good
