### ISSUE TITLE
python3 won't build

### ISSUE THREAD

**Issue by wmertens** [copumpkin/nixpkgs#43]
It fails on configure because it tries to run gcc. Weirdly though, it configures fine under a pure nix-shell.

Also, configure tries to run /usr/bin/sw_vers but that's not available in the sandbox. Not sure if that matters or if it should be a mock that returns data for the pure env.

**Comment by copumpkin** [comment]
Lots of things complain about a missing `sw_vers`. We can provide a dummy one, but I'd rather not lie and just have them deal with the missing value as they see fit.

**Comment by copumpkin** [comment]
I can fix the gcc issue, but then I get a segfault inside the python build, probably related to the usual `macosx-version-min` crap. Will look into it over the weekend.
