### ISSUE TITLE
sw_vers problem

### ISSUE THREAD

**Issue by wavewave** [copumpkin/nixpkgs#57]
My package (ROOT) build uses `sw_vers` for OS X version check. Since `sw_vers` is a native impurity outside nix, how should I address this problem? I found a similar topic like #43 and there seems other packages which has the same problem. What would be the most pure-darwin way to `sw_vers`?

**Comment by copumpkin** [comment]
In an ideal world, no build would even care about the host version. If necessary, we can provide a dummy script that just echoes 10.7 or something like that.

**Comment by wavewave** [comment]
that dummy script idea sounds like a great idea! I will mock up my `sw_vers` and tell how the result goes for my case here.

**Comment by wavewave** [comment]
This issue was now addressed in #58

**Comment by wavewave** [comment]
closing this issue since #58 was merged. Thanks!
