### ISSUE TITLE
dyld: Library not loaded: /usr/lib/libiconv.2.dylib

### ISSUE THREAD

**Issue by datakurre** [copumpkin/nixpkgs#77]
I need some help to get started with pure-darwin branch and sandboxed builds.

I did my best to follow https://nixos.org/wiki/Nix_on_OS_X on OSX 10.10, but

```
nix-env -iA nixpkgs.hello --option build-use-chroot true --option use-binary-caches false
```

fails with

```
building path(s) ‘/nix/store/jsk3pzy9xbblwrnrdplqcl6734r9qcll-bootstrap-tools.9.cpio.bz2’
dyld: Library not loaded: /usr/lib/libiconv.2.dylib
  Referenced from: /nix/store/8qk7fn8icdymgmcmm43vg74kz0wix31g-bash-4.3-p30/bin/bash
  Reason: no suitable image found.  Did find:
	/usr/lib/libiconv.2.dylib: stat() failed with errno=1
	/usr/lib/libiconv.2.dylib: stat() failed with errno=1
builder for ‘/nix/store/p41v2qc4m1gn68mqi4cnmymydffv6aix-bootstrap-tools.9.cpio.bz2.drv’ failed due to signal 5 (Trace/BPT trap: 5)
```

I suppose that the just released nix 1.9 should be enough and development version of nix is no longer needed.

I have OSX 10.10 and CLI tools. Should I remove CLI tools for pure-darwin and sandboxed builds?

**Comment by datakurre** [comment]
My OSX could be a mess after years of use and many OSX upgrades, but that's exactly, why I'm interested in nix with pure sandboxed builds :+)

**Comment by datakurre** [comment]
After installing nix itself from source the same command

    nix-env -iA nixpkgs.hello --option build-use-chroot true --option use-binary-caches false

fails only at

```
make[1]: Leaving directory '/private/var/folders/y6/2zdynm9x3nv6sq5p6780dwdc0000gn/T/nix-build-hello-2.10.drv-0/hello-2.10'
post-installation fixup
gzipping man pages in /nix/store/7n65z86vakwchk4k5azx8svlh5nbqx98-hello-2.10
stripping (with flags -S) in /nix/store/7n65z86vakwchk4k5azx8svlh5nbqx98-hello-2.10/bin 
patching script interpreter paths in /nix/store/7n65z86vakwchk4k5azx8svlh5nbqx98-hello-2.10
building path(s) ‘/nix/store/510djhndflbc7njqb927fzbpi1chrkrx-user-environment’
dyld: Library not loaded: /usr/lib/system/libcache.dylib
  Referenced from: /nix/store/6w6l0gdy7i0hgf1njr0sk59l7q08f4cm-Libsystem-1197.1.1/lib/libSystem.dylib
  Reason: no suitable image found.  Did find:
	/usr/lib/system/libcache.dylib: stat() failed with errno=1
builder for ‘/nix/store/l5aqlj3hy39mi1s469bwa6ph787iwsm2-user-environment.drv’ failed due to signal 5 (Trace/BPT trap: 5)
error: build of ‘/nix/store/l5aqlj3hy39mi1s469bwa6ph787iwsm2-user-environment.drv’ failed
```

**Comment by copumpkin** [comment]
I think what you currently have to do is turn off sandboxed builds in pure-darwin, use it to build a pure version of nix that doesn't reach outside of the store, and then you can use sandboxed builds properly. I haven't touched it in a while so I don't remember the specifics, but perhaps @pikajude or @gridaphobe remember.

**Comment by datakurre** [comment]
I thought, that did just that after the first post: Replaced the default channel with pure-darwin, cloned the current master of nix and installed it with ``nix-env -f release.nix -iA build.x86_64-darwin``. After that I got past the first errors, but still get e.g. that libcache issue.

Well, maybe I start from scratch once again. Yet, welcom any extra tips from @pikajude or @gridaphobe. Would love to get this to work and make this mac a usable development machine again.

**Comment by datakurre** [comment]
Is there some extra required to build a *build a pure version of nix that doesn't reach outside of the store*?

**Comment by spwhitt** [comment]
This problem is a result of this commit: https://github.com/NixOS/nix/commit/6f0c6e20e03bc82fcf0d2198cf81fa2cf25c2f6c

When I attempted to solve the problem by building a pure version of Nix from pure-darwin as @copumpkin suggests, that didn't solve the problem either. It just changed the error to complain about different impurities, because libSystem appears to have impurities of its own.

The simplest workaround is probably to revert the above mentioned commit, build nix, then try with this newly built version of nix. You may also be able to get around it by building stdenv with the chroot turned off, then turning the chroot on for the rest of the builds.

As for a proper fix, I'm not sure the best way to go about implementing it.

**Comment by datakurre** [comment]
@spwhitt Thanks. Would have never found that one. I'll try building stdenv-darwin with the chroot turned off at first.

**Comment by datakurre** [comment]
I didn't have success with just installing stdenv-darwin on top of nix 1.9 and the switching to chroot builds. Now I'm trying with 1.9 and that mentioned patch reversed.

**Comment by datakurre** [comment]
@spwhitt After rebuilding nix with that patch reversed, trying to install a derivation with chroot gives errors like

```
building path(s) ‘/nix/store/jsk3pzy9xbblwrnrdplqcl6734r9qcll-bootstrap-tools.9.cpio.bz2’
error: derivation ‘/nix/store/jmqfyni7vccx90fd8i85rh5ixzns1kzs-bootstrap-tools.9.cpio.bz2.drv’
has ‘__noChroot’ set, but that's not allowed when ‘build-use-chroot’ is ‘true’
```

nix itself was build without chroot, because of dyld errors.

I'm probably still missing some step here. Trying to follow https://nixos.org/wiki/Nix_on_OS_X#Using_the_Development_Branch

**Comment by datakurre** [comment]
Still stucked there. If I install nix 1.9 with https://github.com/NixOS/nix/commit/6f0c6e20e03bc82fcf0d2198cf81fa2cf25c2f6c, I cannot install anything with build-use-chroot.

**Comment by datakurre** [comment]
Any tips, how to get forward? E.g. where should this particular impurity be fixed and how?

```
make[1]: Leaving directory '/private/var/folders/y6/2zdynm9x3nv6sq5p6780dwdc0000gn/T/nix-build-hello-2.10.drv-0/hello-2.10'
post-installation fixup
gzipping man pages in /nix/store/7n65z86vakwchk4k5azx8svlh5nbqx98-hello-2.10
stripping (with flags -S) in /nix/store/7n65z86vakwchk4k5azx8svlh5nbqx98-hello-2.10/bin 
patching script interpreter paths in /nix/store/7n65z86vakwchk4k5azx8svlh5nbqx98-hello-2.10
building path(s) ‘/nix/store/510djhndflbc7njqb927fzbpi1chrkrx-user-environment’
dyld: Library not loaded: /usr/lib/system/libcache.dylib
  Referenced from: /nix/store/6w6l0gdy7i0hgf1njr0sk59l7q08f4cm-Libsystem-1197.1.1/lib/libSystem.dylib
  Reason: no suitable image found.  Did find:
	/usr/lib/system/libcache.dylib: stat() failed with errno=1
builder for ‘/nix/store/l5aqlj3hy39mi1s469bwa6ph787iwsm2-user-environment.drv’ failed due to signal 5 (Trace/BPT trap: 5)
error: build of ‘/nix/store/l5aqlj3hy39mi1s469bwa6ph787iwsm2-user-environment.drv’ failed
```

**Comment by copumpkin** [comment]
There aren't very many people monitoring this thing. You'll probably have better luck on ##nix-darwin IRC, even though it's pretty quiet there too.

**Comment by spwhitt** [comment]
I guess my workarounds don't work. That's unfortunate. We'll have to come up with some other fix for the problem, but I don't have time to put into it at the moment. Good luck!

**Comment by datakurre** [comment]
@pikajude You seem to have been working recently with darwin stdenv https://github.com/pikajude/nixpkgs/tree/bootstrap-darwin Is that the most recent, and how well should that already?

@spwhitt Unfortunately not (or I missed some part). After reversing the patch, I got only "has ‘__noChroot’ set, but that's not allowed when ‘build-use-chroot’ is ‘true’" errors, when trying to use sandboxing. Building stdenv (from pure-darwin) with chroot turned off, didn't seem to have any effect.

@copumpkin I'll be there (nix-darwin), when I've lost all hope :)

**Comment by pikajude** [comment]
For anyone concerned, you can set `build-use-chroot = relaxed` to allow the usage of "__noChroot" if you need to

**Comment by datakurre** [comment]
@pikajude @spwhitt I'll try out re-building nix with that mentioned patch reverted and then using ``build-use-chroot = relaxed`` with ``pure-darwin`` branch of nixpkgs.

**Comment by datakurre** [comment]
@spwhitt re-building nix with that patch reversed and setting ``build-use-chroot = relaxed`` seems to get me forward.

I'll see after weekend, how packages pure-darwin packages build with chroot = relaxed.

**Comment by datakurre** [comment]
Finally I seem to be able to do sandboxed darwin builds with the following steps after clean Nix 1.9 install:

1. Replace the default channel with nixpkgs staging
2. Enable darwin pure stdenv by configuring it in ~/.nixpkgs/config.nix

        { 
            replaceStdenv = {pkgs}: pkgs.allStdenvs.stdenvDarwinPure
        }

3. Re-build nix from checkout with https://github.com/NixOS/nix/commit/6f0c6e20e03bc82fcf0d2198cf81fa2cf25c2f6c reversed and ``build-use-chroot = false`` in ``etc/nix/nix.conf`` by ``nix-env -f release.nix -iA build.x86_64-darwin``
4. Build packages with ``build-use-chroot = relaxed``

I think, I also did ``nix-collect-garbage -d`` almost between each step, but not sure when it's really needed.

Thanks to @spwhitt and @pikajude.
